import { Inter } from 'next/font/google';
import localfont from 'next/font/local';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const ginto = localfont({
  src: '../public/fonts/ginto/ABCGintoNormalVariable-Trial.ttf',
  variable: '--font-ginto',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${ginto.variable}`}>{children}</body>
    </html>
  );
}
